# This is a basic workflow to help you get started with Actions

name: ContentReplacer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: ls from main.yml
        run: ls

      - name: action1
        id: action1
        uses: ./.github/actions/action1

      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
        shell: bash

      # Show file content
      - name: Show README.md content
        run: echo "$(<README.md)"