name: Update README.md

on:
  workflow_dispatch:

jobs:
  update-readme-sample:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: action1
        id: action1
        uses: ./.github/actions/action1
        with:
          medium-user-id: ${{ secrets.MEDIUM_USER_ID }}
          stackoverflow-user-id: ${{ secrets.STACKOVERFLOW_USER_ID }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
        shell: bash

      - name: Show README.md content
        run: echo "$(<README.md)"